
/*
This program uses random numbers to conduct numerical simulations
Also known as the Monte Carlo method.

An integral is used to represent PI/4.
The integral is used to approximate the area of the shaded area.

A pair of two random numbers (x,y) with values ranging between
0 and 1 are generated by N times and will be used as the point.

Every Nth time, if the point satisifies [x^2 + y^2 < 1] the point
is inside the shaded area increment a counter by 1.

At the end of N rounds, the value of i/N should be proportional to the
shaded area/the square.

As N increases, it is expect that the ratio of i/N is close to PI/4.
*/

#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

int main()
{
    double x, y;
    int i, n, count = 0;

    // 1. Get the iteration number (N) from the user's input.
    printf("Enter iteration number (N) = ");
    scanf("%d", &n);

    // 2. Set the seed for the number randomizer.
    srand(time(NULL));

    for (i = 0; i < n; i++)
    {
        x = 1.0 * rand() / RAND_MAX;
        y = 1.0 * rand() / RAND_MAX;

        // 3. Check if the points satisfy the formula.
        if (x * x + y * y < 1.0)
        {
            count++;
        }
    }

    // 3. Display results
    double result = (double)count / n;

    printf("True value = %.30lf\n", M_PI_4);
    printf("Appx value = %.30lf\n", result);
    printf("Diff value = %.30lf\n", M_PI_4 - result);

    return 0;
}